# PodScaler yml file configuration
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: gke-tutorial-hpa
  namespace: default
  labels:
    app: sftp-background-service
spec:
  scaleTargetRef:
    kind: Deployment
    name: sftp-background-service
    apiVersion: apps/v1beta1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80